### ISSUE TITLE
05.Task- Make Move(POST)

### ISSUE THREAD

**Issue by alina-idk** [AlinaNgr/FinalProjectTicTacToe#7]
-  Implementarea unui endpoint POST care să permită unui utilizator să facă o mișcare într-un joc existent.
 
-  Endpoint-ul va accepta:

-  game_id (id-ul jocului),

-  Mișcarea (rândul și coloana).

- Verificarea validității mișcării (ex: celula nu este deja ocupată).

-   Actualizarea stării jocului în baza de date.

-  Verificarea dacă există un câștigător după fiecare mișcare și returnarea rezultatului (câștigător sau egal).

- **_Va răspunde cu starea actuală a jocului._**

**Comment by AlinaNgr** [comment]
Un endpoint care sa indeplineasca toate aceste cerinte a fost adaugat.
