### ISSUE TITLE
07.Task- User Authentication

### ISSUE THREAD

**Issue by alina-idk** [AlinaNgr/FinalProjectTicTacToe#9]
- Implementarea unui sistem de autentificare bazat pe sessions.

- Crearea unui endpoint pentru înregistrare (crearea unui cont) și autentificare (login).

**Comment by AlinaNgr** [comment]
from fastapi.openapi.utils import get_openapi

def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema

    # Generăm schema OpenAPI implicită
    openapi_schema = get_openapi(
        title="My API",
        version="1.0.0",
        description="API description",
        routes=app.routes,
    )

    if "components" in openapi_schema:
        openapi_schema["components"].pop("securitySchemes", None)

    openapi_schema.pop("security", None)


    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi


@app.post("/login")
def login(user: UserCreate, request: Request, db: Session = Depends(get_db)):
    db_user = get_user_by_username(db, user.username)
    if db_user is None or db_user.password != user.password:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Invalid credentials")

    request.session['user_id'] = db_user.id  # Set user_id in session

    games = db.query(GameState).filter(GameState.user_id == db_user.id).all()
    game_list = [{"game_id": game.id, "board": json.loads(game.board), "current_player": game.current_player} for game in games]

    return {"message": "Login successful", "games": game_list}

@app.post("/logout")
def logout(request: Request):
    request.session.clear()  # Clear session
    return {"message": "Logout successful"}

# Protected endpoints

@app.post("/register", response_model=Client)
def register(user: UserCreate, db: Session = Depends(get_db)):
    return create_user(db, user)
